### ISSUE TITLE
Opacity Plugin is Outputting "Array" instead of values

### ISSUE THREAD

**Issue by rodp82** [TurbineCSS/Turbine#178]
The opacity plugin is outputting CSS like

``` CSS
div.something {
    -moz-opacity: Array; /* Added by opacity plugin */
    -webkit-opacity: Array; /* Added by opacity plugin */
    -khtml-opacity: Array; /* Added by opacity plugin */
    opacity: 0.7;
}
```

Issue comes from line 35 of the Opacity plugin:

``` PHP
$opacity_properties[$prefix.'opacity'][] = $parsed[$block][$selector]['opacity'];
```

change to:

``` PHP
$opacity_properties[$prefix.'opacity'] = $parsed[$block][$selector]['opacity'];
```
